# Generated by Django 5.2.3 on 2026-06-12 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='user_role_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('mobile_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userrole')),
            ],
        ),
    ]
