# Generated by Django 5.2.3 on 2026-06-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userrole_user_role_description_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
