# Generated by Django 5.2.3 on 2026-06-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_registeruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='reset_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
