# Generated by Django 5.2.3 on 2026-06-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_registeruser_reset_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('scholarship_id', models.AutoField(primary_key=True, serialize=False)),
                ('scholarship_name', models.CharField(max_length=255)),
                ('provider_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('education_level', models.CharField(max_length=100)),
                ('eligibility', models.TextField()),
                ('description', models.TextField()),
                ('application_deadline', models.DateField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
