# Generated by Django 5.2.3 on 2026-06-18 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_scholarship'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedScholarship',
            fields=[
                ('saved_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.scholarship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.registeruser')),
            ],
        ),
    ]
